server:
  port: 9999
spring:
  application:
    name: king-gateway
  profiles:
    active: dev
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.14.162:8848
      #        namespace: 1fe8f6d3-f5aa-4de4-ae07-57cfa21f600f
      #        cluster-name: nanjing
    gateway:
      discovery:
        locator:
          # 让gateway通过服务发现组件找到其他微服务
          enabled: true
          lower-case-service-id: true
#      config:
#        server-addr: 127.0.0.1:8848
#        file-extension: yml
#        shared-configs:
#          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
#  redis:
#    host: 106.13.105.158
#    port: 6379
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

