server:
  port: 9000
spring:
  application:
    name: king-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wanniwa/config-repo.git
          username: 734933034@qq.com
          password: N1i9n9g3
    bus:
      enabled: true
  rabbitmq:
    host: 106.13.105.158
    port: 5672
    username: guest
    password: wang1993
eureka:
  client:
    service-url:
      defaultZone: http://wanniwa:wang1993@106.13.105.158:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
management:
  endpoints:
    web:
      exposure:
        include: "*"
