server:
  port: 8761
spring:
  application:
    name: king-erueka
  security:
    user:
      name: wanniwa
      password: wang1993

eureka:
  client:
    #是否从eureka服务器获取注册信息
    fetch-registry: false
    #是否向服务注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: http://wanniwa:wang1993@127.0.0.1:${server.port}/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true
    #server:
    #enable-self-preservation: false #关闭自我保护机制
  server:
    eviction-interval-timer-in-ms: 30000
    enable-self-preservation: false
#    renewal-percent-threshold: 0.9
