server:
  port: 9001
spring:
  application:
    name: king-product
eureka:
  client:
    #是否从eureka服务器获取注册信息
    fetch-registry: false
    #是否向服务注册中心注册自己
    register-with-eureka: false
    service-url:
      defaultZone: ${eureka.instance.hostname}:${server.port}/eureka
  instance:
    hostname: http://localhost