#开发环境配置
server:
  #端口
  port: 8011
spring:
  application:
    name: king-upms-biz
  cloud:
    nacos:
      discovery:
        server-addr: 122.51.14.162:8848
      #        namespace: 1fe8f6d3-f5aa-4de4-ae07-57cfa21f600f
      #        cluster-name: nanjing
      config:
        server-addr: 122.51.14.162:8848
        file-extension: yml
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}
  redis:
    host: 122.51.14.162
    port: 6379
    password: wang1993
  datasource:
    url: jdbc:mysql://localhost:3306/king?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC&useSSL=false&tinyInt1isBit=true&allowPublicKeyRetrieval=true&autoReconnect=true
    username: root
    password: root123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  #ribbon:
#  eager-load:
#     enabled: true




#security:
#  oauth2:
#    client:
#      client-id: client_2
#      client-secret: 123456
#      scope: all
#      grant-type: client_credentials
#    resource:
#      token-info-uri: http://127.0.0.1:9000/oauth/check_token
#      id: 111


security:
  oauth2:
    client:
      client-id: client_1
      client-secret: 123456
      scope: all
      grant-type: client_credentials
    resource: # 认证中心的check_token 接口地址
      token-info-uri: http://127.0.0.1:9000/oauth/check_token
#logging:
#  level:

feign:
  sentinel:
    enabled: true
  client:
    config:
      default:
        logger-level: basic
  httpclient:
    # 让feign使用apache httpclient做请求，而不是url connection
    enabled: true
    # feign的最大连接数
    max-connections: 200
    # feign单个路径的最大连接数
    max-connections-per-route: 50
#  okhttp:
#    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: '*'
#security:
#  oauth2:
#    ignore: 'ssss'

